In [3]:
import numpy as np
import matplotlib.pyplot as plt
import synthetic_data


# context_generator = QuinticContexts()
context_generator = synthetic_data.BullsEyeContexts2()
# context_generator = synthetic_data.MixtureContexts()
donut_samples = []
other_samples = []
all = []
for _ in range(1000000):
    c, d = context_generator.get_context()
    if d[0]>0.5:
        donut_samples.append(c)
    else:
        other_samples.append(c)

    all.append(c)

donut_samples = np.array(donut_samples).squeeze(1)
other_samples = np.array(other_samples).squeeze(1)

# all = np.array(all)
# Plot the samples
# plt.figure(figsize=(6, 6))
# plt.scatter(other_samples[:, 0], other_samples[:, 1], color='blue', label='Other Samples')
# plt.scatter(donut_samples[:, 0], donut_samples[:, 1], color='orange', label='Donut Samples')
# plt.xlim(-1, 1)
# plt.ylim(-1, 1)
# plt.xlabel('X')
# plt.ylabel('Y')
# plt.title('Uniform Samples and Donut Samples')
# plt.legend()
# plt.show()
# # plt.savefig('./bullseye.png',dpi = 380)

# print( len(donut_samples)/ ( len(donut_samples)+len(other_samples) ) )

In [4]:
np.mean(all,0)

array([[0.00031191, 0.00048158]])

In [5]:
np.std(all,0)

array([[0.57730562, 0.57743101]])

In [6]:
donut_samples

array([[[-0.23068365, -0.23068365, -0.14009862, -0.14009862,
         -0.14009862]],

       [[-0.33303447, -0.33303447,  0.19365482,  0.19365482,
          0.19365482]],

       [[ 0.06928705,  0.06928705,  0.24679116,  0.24679116,
          0.24679116]],

       ...,

       [[-0.33821717, -0.33821717,  0.17067736,  0.17067736,
          0.17067736]],

       [[ 0.04858651,  0.04858651,  0.19476084,  0.19476084,
          0.19476084]],

       [[-0.23656935, -0.23656935, -0.20217409, -0.20217409,
         -0.20217409]]])